[package]
name = "file_log"
version = "0.1.0"
edition = "2021"
description = "A library to write logs to files with an index."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8"
